batch_size: 32
block_size: 512
data_path: /content/all_transcripts_merged.txt
device: cuda
dropout: 0.1
epochs: 15
grammar_repeat: 8
learning_rate: 0.0004
max_steps: null
n_embd: 512
n_head: 8
n_layer: 8
val_split: 0.1
vocab_size: 6000
